/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Win1O
 */
public class MenuGUI extends javax.swing.JFrame {
    
    private Integer jmlPotongRambutAnak = 0;
    private Integer jmlPotongRambutRemaja = 0;
    private Integer jmlPotongRambutDewasa = 0;
    private Integer jmlCukurKumis = 0;
    private Integer jmlCukurJanggut = 0;
    private Integer jmlKeramasPijat = 0;
    private Integer jmlMaskerRambut = 0;
    private Integer jmlSemirRambut = 0;

    /**
     * Creates new form MenuGUI
     */
    public MenuGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField11 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TextFieldPotongRambutAnak = new javax.swing.JTextField();
        TextFieldPotongRambutRemaja = new javax.swing.JTextField();
        TextFieldPotongRambutDewasa = new javax.swing.JTextField();
        ButtonTambahAnak = new javax.swing.JButton();
        ButtonKurangAnak = new javax.swing.JButton();
        ButtonTambahRemaja = new javax.swing.JButton();
        ButtonKurangRemaja = new javax.swing.JButton();
        ButtonTambahDewasa = new javax.swing.JButton();
        ButtonKurangDewasa = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TextFieldCukurKumis = new javax.swing.JTextField();
        ButtonTambahCukurKumis = new javax.swing.JButton();
        ButtonKurangCukurKumis = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TextFieldCukurJenggot = new javax.swing.JTextField();
        ButtonTambahCukurJenggot = new javax.swing.JButton();
        ButtonKurangCukurJenggot = new javax.swing.JButton();
        TextFieldKeramasPijat = new javax.swing.JTextField();
        ButtonTambahKeramasPijat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ButtonKurangKeramasPijat = new javax.swing.JButton();
        TextFieldMaskerRambut = new javax.swing.JTextField();
        ButtonTambahMaskerRambut = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        ButtonKurangMaskerRambut = new javax.swing.JButton();
        ButtonKurangSemirRambut = new javax.swing.JButton();
        TextFieldSemirRambut = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ButtonTambahSemirRambut = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        TextFieldIsiNama = new javax.swing.JTextField();
        TextFieldIsiNoKursi = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAreaTotalBelanja = new javax.swing.JTextArea();
        jButton22 = new javax.swing.JButton();
        TextFieldBayar = new javax.swing.JTextField();
        jButton23 = new javax.swing.JButton();

        jTextField11.setText("jTextField11");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(153, 153, 255));

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jButton2.setBackground(new java.awt.Color(102, 102, 255));
        jButton2.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/gunting2.png"))); // NOI18N
        jButton2.setText("BARBERSHOP KONOHA");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("PILIHAN");
        jButton1.setBorder(null);

        jButton3.setBackground(new java.awt.Color(102, 102, 255));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("TAMBAHAN");
        jButton3.setBorder(null);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText(" Potong Rambut Dewasa");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText(" Potong Rambut Anak");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setText(" Potong Rambut Remaja");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TextFieldPotongRambutAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPotongRambutAnakActionPerformed(evt);
            }
        });

        TextFieldPotongRambutRemaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPotongRambutRemajaActionPerformed(evt);
            }
        });

        TextFieldPotongRambutDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldPotongRambutDewasaActionPerformed(evt);
            }
        });

        ButtonTambahAnak.setText("+");
        ButtonTambahAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahAnakActionPerformed(evt);
            }
        });

        ButtonKurangAnak.setText("-");
        ButtonKurangAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangAnakActionPerformed(evt);
            }
        });

        ButtonTambahRemaja.setText("+");
        ButtonTambahRemaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahRemajaActionPerformed(evt);
            }
        });

        ButtonKurangRemaja.setText("-");
        ButtonKurangRemaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangRemajaActionPerformed(evt);
            }
        });

        ButtonTambahDewasa.setText("+");
        ButtonTambahDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahDewasaActionPerformed(evt);
            }
        });

        ButtonKurangDewasa.setText("-");
        ButtonKurangDewasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangDewasaActionPerformed(evt);
            }
        });

        jLabel4.setText(" Cukur Kumis");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TextFieldCukurKumis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCukurKumisActionPerformed(evt);
            }
        });

        ButtonTambahCukurKumis.setText("+");
        ButtonTambahCukurKumis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahCukurKumisActionPerformed(evt);
            }
        });

        ButtonKurangCukurKumis.setText("-");
        ButtonKurangCukurKumis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangCukurKumisActionPerformed(evt);
            }
        });

        jLabel5.setText(" CukurJenggot");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TextFieldCukurJenggot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldCukurJenggotActionPerformed(evt);
            }
        });

        ButtonTambahCukurJenggot.setText("+");
        ButtonTambahCukurJenggot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahCukurJenggotActionPerformed(evt);
            }
        });

        ButtonKurangCukurJenggot.setText("-");
        ButtonKurangCukurJenggot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangCukurJenggotActionPerformed(evt);
            }
        });

        TextFieldKeramasPijat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldKeramasPijatActionPerformed(evt);
            }
        });

        ButtonTambahKeramasPijat.setText("+");
        ButtonTambahKeramasPijat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahKeramasPijatActionPerformed(evt);
            }
        });

        jLabel6.setText(" Keramas + Pijat");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonKurangKeramasPijat.setText("-");
        ButtonKurangKeramasPijat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangKeramasPijatActionPerformed(evt);
            }
        });

        TextFieldMaskerRambut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldMaskerRambutActionPerformed(evt);
            }
        });

        ButtonTambahMaskerRambut.setText("+");
        ButtonTambahMaskerRambut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahMaskerRambutActionPerformed(evt);
            }
        });

        jLabel7.setText(" Masker Rambut");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonKurangMaskerRambut.setText("-");
        ButtonKurangMaskerRambut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangMaskerRambutActionPerformed(evt);
            }
        });

        ButtonKurangSemirRambut.setText("-");
        ButtonKurangSemirRambut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonKurangSemirRambutActionPerformed(evt);
            }
        });

        TextFieldSemirRambut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextFieldSemirRambutActionPerformed(evt);
            }
        });

        jLabel8.setText(" Semir Rambut");
        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ButtonTambahSemirRambut.setText("+");
        ButtonTambahSemirRambut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonTambahSemirRambutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextFieldPotongRambutAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ButtonTambahAnak)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ButtonKurangAnak))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextFieldCukurKumis, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonTambahCukurKumis)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonKurangCukurKumis))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(TextFieldPotongRambutDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(TextFieldPotongRambutRemaja, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(ButtonTambahRemaja)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ButtonKurangRemaja))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(ButtonTambahDewasa)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ButtonKurangDewasa))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextFieldCukurJenggot, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonTambahCukurJenggot)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonKurangCukurJenggot))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextFieldKeramasPijat, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonTambahKeramasPijat)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonKurangKeramasPijat))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextFieldMaskerRambut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonTambahMaskerRambut)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonKurangMaskerRambut))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(TextFieldSemirRambut, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ButtonTambahSemirRambut)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ButtonKurangSemirRambut))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldPotongRambutAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahAnak)
                    .addComponent(ButtonKurangAnak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ButtonTambahRemaja)
                        .addComponent(ButtonKurangRemaja))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldPotongRambutRemaja, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextFieldPotongRambutDewasa, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonTambahDewasa)
                            .addComponent(ButtonKurangDewasa))))
                .addGap(8, 8, 8)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCukurKumis, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahCukurKumis)
                    .addComponent(ButtonKurangCukurKumis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldCukurJenggot, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahCukurJenggot)
                    .addComponent(ButtonKurangCukurJenggot))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldKeramasPijat, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahKeramasPijat)
                    .addComponent(ButtonKurangKeramasPijat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldMaskerRambut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahMaskerRambut)
                    .addComponent(ButtonKurangMaskerRambut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldSemirRambut, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonTambahSemirRambut)
                    .addComponent(ButtonKurangSemirRambut))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText(" Nama");
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel10.setText(" No. Kursi");
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextFieldIsiNama, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldIsiNoKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldIsiNama, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldIsiNoKursi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton20.setBackground(new java.awt.Color(102, 102, 255));
        jButton20.setForeground(new java.awt.Color(255, 255, 255));
        jButton20.setText("Data Diri");
        jButton20.setBorder(null);
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });

        jButton21.setBackground(new java.awt.Color(102, 102, 255));
        jButton21.setForeground(new java.awt.Color(255, 255, 255));
        jButton21.setText("Total");
        jButton21.setBorder(null);

        TextAreaTotalBelanja.setColumns(20);
        TextAreaTotalBelanja.setRows(5);
        TextAreaTotalBelanja.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(TextAreaTotalBelanja);

        jButton22.setBackground(new java.awt.Color(102, 102, 255));
        jButton22.setForeground(new java.awt.Color(255, 255, 255));
        jButton22.setText("Bayar");
        jButton22.setBorder(null);

        TextFieldBayar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton23.setBackground(new java.awt.Color(102, 102, 255));
        jButton23.setForeground(new java.awt.Color(255, 255, 255));
        jButton23.setText("Next");
        jButton23.setBorder(null);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextFieldBayar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jButton21, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TextFieldBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ButtonTambahAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahAnakActionPerformed
        // TODO add your handling code here:
        jmlPotongRambutAnak += 1;
        TextFieldPotongRambutAnak.setText(jmlPotongRambutAnak.toString());
    }//GEN-LAST:event_ButtonTambahAnakActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton20ActionPerformed

    private void TextFieldPotongRambutAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPotongRambutAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPotongRambutAnakActionPerformed

    private void ButtonKurangAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangAnakActionPerformed
        // TODO add your handling code here:
        if(jmlPotongRambutAnak>0){
            jmlPotongRambutAnak -= 1;
            TextFieldPotongRambutAnak.setText(jmlPotongRambutAnak.toString());
        }
    }//GEN-LAST:event_ButtonKurangAnakActionPerformed

    private void ButtonTambahRemajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahRemajaActionPerformed
        // TODO add your handling code here:
        jmlPotongRambutRemaja += 1;
        TextFieldPotongRambutRemaja.setText(jmlPotongRambutRemaja.toString());
    }//GEN-LAST:event_ButtonTambahRemajaActionPerformed

    private void TextFieldPotongRambutRemajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPotongRambutRemajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPotongRambutRemajaActionPerformed

    private void ButtonKurangRemajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangRemajaActionPerformed
        // TODO add your handling code here:
        if(jmlPotongRambutRemaja>0){
            jmlPotongRambutRemaja -= 1;
            TextFieldPotongRambutRemaja.setText(jmlPotongRambutRemaja.toString());
        }
    }//GEN-LAST:event_ButtonKurangRemajaActionPerformed

    private void ButtonTambahDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahDewasaActionPerformed
        // TODO add your handling code here:
        jmlPotongRambutDewasa += 1;
        TextFieldPotongRambutDewasa.setText(jmlPotongRambutDewasa.toString());
    }//GEN-LAST:event_ButtonTambahDewasaActionPerformed

    private void TextFieldPotongRambutDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldPotongRambutDewasaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldPotongRambutDewasaActionPerformed

    private void ButtonKurangDewasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangDewasaActionPerformed
        // TODO add your handling code here:
        if(jmlPotongRambutDewasa>0){
            jmlPotongRambutDewasa -= 1;
            TextFieldPotongRambutDewasa.setText(jmlPotongRambutDewasa.toString());
        }
    }//GEN-LAST:event_ButtonKurangDewasaActionPerformed

    private void ButtonTambahCukurKumisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahCukurKumisActionPerformed
        // TODO add your handling code here:
        jmlCukurKumis += 1;
        TextFieldCukurKumis.setText(jmlCukurKumis.toString());
    }//GEN-LAST:event_ButtonTambahCukurKumisActionPerformed

    private void TextFieldCukurKumisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCukurKumisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCukurKumisActionPerformed

    private void ButtonKurangCukurKumisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangCukurKumisActionPerformed
        // TODO add your handling code here:
        if(jmlCukurKumis>0){
            jmlCukurKumis -= 1;
            TextFieldCukurKumis.setText(jmlCukurKumis.toString());
        }
    }//GEN-LAST:event_ButtonKurangCukurKumisActionPerformed

    private void ButtonTambahCukurJenggotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahCukurJenggotActionPerformed
        // TODO add your handling code here:
        jmlCukurJanggut += 1;
        TextFieldCukurJenggot.setText(jmlCukurJanggut.toString());
    }//GEN-LAST:event_ButtonTambahCukurJenggotActionPerformed

    private void TextFieldCukurJenggotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldCukurJenggotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldCukurJenggotActionPerformed

    private void ButtonKurangCukurJenggotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangCukurJenggotActionPerformed
        // TODO add your handling code here:
        if(jmlCukurJanggut>0){
            jmlCukurJanggut -= 1;
            TextFieldCukurJenggot.setText(jmlCukurJanggut.toString());
        }
    }//GEN-LAST:event_ButtonKurangCukurJenggotActionPerformed

    private void ButtonTambahKeramasPijatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahKeramasPijatActionPerformed
        // TODO add your handling code here:
        jmlKeramasPijat += 1;
        TextFieldKeramasPijat.setText(jmlKeramasPijat.toString());
    }//GEN-LAST:event_ButtonTambahKeramasPijatActionPerformed

    private void TextFieldKeramasPijatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldKeramasPijatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldKeramasPijatActionPerformed

    private void ButtonKurangKeramasPijatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangKeramasPijatActionPerformed
        // TODO add your handling code here:
        if(jmlKeramasPijat>0){
            jmlKeramasPijat -= 1;
            TextFieldKeramasPijat.setText(jmlKeramasPijat.toString());
        }
        
    }//GEN-LAST:event_ButtonKurangKeramasPijatActionPerformed

    private void TextFieldMaskerRambutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldMaskerRambutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldMaskerRambutActionPerformed

    private void ButtonTambahMaskerRambutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahMaskerRambutActionPerformed
        // TODO add your handling code here:
        jmlMaskerRambut += 1;
        TextFieldMaskerRambut.setText(jmlMaskerRambut.toString());
    }//GEN-LAST:event_ButtonTambahMaskerRambutActionPerformed

    private void ButtonKurangMaskerRambutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangMaskerRambutActionPerformed
        // TODO add your handling code here:
        if(jmlMaskerRambut>0){
            jmlMaskerRambut -= 1;
            TextFieldMaskerRambut.setText(jmlMaskerRambut.toString());
        }
    }//GEN-LAST:event_ButtonKurangMaskerRambutActionPerformed

    private void TextFieldSemirRambutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextFieldSemirRambutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextFieldSemirRambutActionPerformed

    private void ButtonTambahSemirRambutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonTambahSemirRambutActionPerformed
        // TODO add your handling code here:
        jmlSemirRambut += 1;
        TextFieldSemirRambut.setText(jmlSemirRambut.toString());
    }//GEN-LAST:event_ButtonTambahSemirRambutActionPerformed

    private void ButtonKurangSemirRambutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonKurangSemirRambutActionPerformed
        // TODO add your handling code here:
        if(jmlSemirRambut>0){
            jmlSemirRambut -= 1;
            TextFieldSemirRambut.setText(jmlSemirRambut.toString());
        }
    }//GEN-LAST:event_ButtonKurangSemirRambutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonKurangAnak;
    private javax.swing.JButton ButtonKurangCukurJenggot;
    private javax.swing.JButton ButtonKurangCukurKumis;
    private javax.swing.JButton ButtonKurangDewasa;
    private javax.swing.JButton ButtonKurangKeramasPijat;
    private javax.swing.JButton ButtonKurangMaskerRambut;
    private javax.swing.JButton ButtonKurangRemaja;
    private javax.swing.JButton ButtonKurangSemirRambut;
    private javax.swing.JButton ButtonTambahAnak;
    private javax.swing.JButton ButtonTambahCukurJenggot;
    private javax.swing.JButton ButtonTambahCukurKumis;
    private javax.swing.JButton ButtonTambahDewasa;
    private javax.swing.JButton ButtonTambahKeramasPijat;
    private javax.swing.JButton ButtonTambahMaskerRambut;
    private javax.swing.JButton ButtonTambahRemaja;
    private javax.swing.JButton ButtonTambahSemirRambut;
    private javax.swing.JTextArea TextAreaTotalBelanja;
    private javax.swing.JTextField TextFieldBayar;
    private javax.swing.JTextField TextFieldCukurJenggot;
    private javax.swing.JTextField TextFieldCukurKumis;
    private javax.swing.JTextField TextFieldIsiNama;
    private javax.swing.JTextField TextFieldIsiNoKursi;
    private javax.swing.JTextField TextFieldKeramasPijat;
    private javax.swing.JTextField TextFieldMaskerRambut;
    private javax.swing.JTextField TextFieldPotongRambutAnak;
    private javax.swing.JTextField TextFieldPotongRambutDewasa;
    private javax.swing.JTextField TextFieldPotongRambutRemaja;
    private javax.swing.JTextField TextFieldSemirRambut;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField11;
    // End of variables declaration//GEN-END:variables
}
